#include "main.h"

#include <stdio.h>
#include <stdlib.h>
#include "images/soccer_field.h"
#include "images/soccer_goal.h"
#include "images/messi_title_image.h"
#include "images/ball.h"
#include "images/player_messi.h"
#include "images/player_messi1.h"
#include "images/messi.h"
#include "images/ronaldo.h"
#include "images/referee.h"
#include "images/gameover_lose.h"
#include "images/win_world_cup.h"
#include "images/red_card.h"

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  TITLE,
  SETUP,
  START,
  PLAY,
  WIN,
  LOSE,
  REF
};

int collide(int rowOne, int colOne, int widthOne, int heightOne, int rowTwo, int colTwo, int widthTwo, int heightTwo) {
  if (colOne < colTwo + widthTwo && colOne + widthOne > colTwo && rowOne < rowTwo + heightTwo && rowOne + heightOne > rowTwo) {
    return 1;
  }
  return 0;
}

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3|BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;
  struct player mainPlayer = {0, 0};
  struct player defender = {0, 0};
  struct player refereeDim = {0, 0};
  int ballRow = 0;
  int ballCol = 0;
  int prevRow = 0;
  int prevCol = 0;
  // int goalRow = 100;
  // int goalCol = 100;
  int userScore = 0;
  int oppScore = 0;
  int redCardCounter = 0;

  //for ball animation
  int ballVel = 1;
  int ballDir = 1;
  int ballX = 0;
  // int ballPrevRow = 0;
  // int ballPrevCol = 0;

 waitForVBlank();
 drawFullScreenImageDMA(messi_title_image);
 drawString(20, 50, "Welcome to FIFA 2110", WHITE);
 drawString(45, 55, "Click Enter to play", WHITE);
state = TITLE;



  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();

    switch (state) {
      case TITLE:  
        //reset scores
        userScore = 0;
        oppScore = 0;
        redCardCounter = 0;     
        //ball animation

        // Update ball position for animation
        ballX += ballVel * ballDir;

        // Reverse direction if ball reaches screen boundaries
        if (ballX <= 0 || ballX >= 240 - BALL_WIDTH) {
          ballDir *= -1;
        }

        // Draw the ball at its current position
        drawImageDMA(160 / 2 - BALL_HEIGHT / 2, ballX, BALL_WIDTH, BALL_HEIGHT, ball);
        //drawImageWithTransparency(160 / 2 - BALL_HEIGHT / 2, ballX, BALL_WIDTH, BALL_HEIGHT, ball, BLACK); 
        // drawRectDMA(ballPrevRow, ballPrevCol, 25, 25, background_color);


        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons) != 0) {
          state = SETUP;
        }



        break;
      case SETUP:
        drawFullScreenImageDMA(messi_title_image);

        //display current scoreboard        
        drawInt(60, 75, userScore, WHITE);
        drawString(60, 100, "-", WHITE);        
        drawInt(60, 125, oppScore, WHITE);

        drawString(80, 75, "Red Cards:", WHITE);
        drawInt(80, 140, redCardCounter, WHITE);
        if(KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons) != 0){
          state = TITLE;
          vBlankCounter = 0;

          drawFullScreenImageDMA(messi_title_image);
          drawString(20, 50, "Welcome to FIFA 2110", WHITE);
          drawString(45, 55, "Click Enter to play", WHITE);
        } else {
          state = START;
        }

        break;

      case START:
 

      if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons) != 0) {
        state = PLAY;
        //drawRectDMA(0, 0, 240, 160, GREEN);
        //drawFullScreenImageDMA(soccer_field);
        drawRectDMA(0, 0, 240, 160, BLACK);


        //draw goal centered and at bottom of screen
        //drawImageDMA(goalRow, goalCol, 50, 27, soccer_goal);

        

        //set player init position
        mainPlayer.row = 0;
        mainPlayer.col = 0;
        
        //set defender init position
        defender.row = randint(26, 120);
        defender.col = randint(26, 190);

        //set defender init position
        refereeDim.row = randint(26, 120);
        refereeDim.col = randint(26, 190);

        //randomly spawn ball
        ballRow = randint(26, 120); 
        ballCol= randint(26, 190);

        //if defender, referee, or ball overlaps 
        while(refereeDim.row == defender.row || refereeDim.col == defender.col || ballRow == defender.row || 
        ballCol == defender.col || ballRow == refereeDim.row || ballCol == refereeDim.col){
          //set defender init position
          defender.row = randint(26, 120);
          defender.col = randint(26, 190);

          //set defender init position
          refereeDim.row = randint(26, 120);
          refereeDim.col = randint(26, 190);

          //randomly spawn ball
          ballRow = randint(26, 120); 
          ballCol= randint(26, 190);
        }
        

        //drawImageWithTransparency(ballRow, ballCol, 25, 25, ball, BLACK);
        drawImageDMA(ballRow, ballCol, 25, 25, ball);

        //draw defender
        // drawImageWithTransparency(defender.row, defender.col, 25, 25, ronaldo, BLACK);
        drawImageDMA(defender.row, defender.col, 25, 25, ronaldo);

        //draw referee
        // drawImageWithTransparency(refereeDim.row, refereeDim.col, 25, 25, referee, BLACK);
        drawImageDMA(refereeDim.row, refereeDim.col, 25, 25, referee);


      }
        break;

      case PLAY:
                
        // drawFullScreenImageDMA(soccer_field);

        prevRow = mainPlayer.row;
        prevCol = mainPlayer.col;

        
        drawImageDMA(mainPlayer.row, mainPlayer.col, 25, 25, player_messi1);
        
        // drawImageWithTransparency(mainPlayer.row, mainPlayer.col, 25, 25, player_messi1, BLACK);

        
        undrawImageDMA(prevRow, prevCol, 25, 25, soccer_field);

        //player movement
        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          mainPlayer.row = mainPlayer.row - 1;
        }

        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          mainPlayer.row = mainPlayer.row + 1;
        }

        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          mainPlayer.col = mainPlayer.col - 1;
        }

        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          mainPlayer.col = mainPlayer.col + 1;
        }


        //if player collides with defender -> oppscore++
        if (collide(mainPlayer.row, mainPlayer.col, 25, 25, defender.row, defender.col, 25, 25) == 1) {
          oppScore++;
          if(oppScore == 5){
            state = LOSE;
            drawFullScreenImageDMA(gameover_lose);
                 
          } else {
            state = SETUP;
          }

        }

        //if player collides with referee -> red card
        if (collide(mainPlayer.row, mainPlayer.col, 25, 25, refereeDim.row, refereeDim.col, 25, 25) == 1) {
          redCardCounter++;
          if(redCardCounter == 5){
            state = REF;
            drawFullScreenImageDMA(red_card);
          } else {
            state = SETUP;
          }
        }
        //if player scores -> userScore++
        if (collide(mainPlayer.row, mainPlayer.col, 25, 25, ballRow, ballCol, 25, 25) == 1) {
          userScore++;
          if(userScore == 5){
            state = WIN;
            drawFullScreenImageDMA(win_world_cup);         
          } else {
            state = SETUP;
          }

        }

        //handle wall boundaries
        if (mainPlayer.col < 0) {
            mainPlayer.col = 0;
        } else if (mainPlayer.col > 215) {
            mainPlayer.col = 215;
        }

        if (mainPlayer.row < 0) {
            mainPlayer.row = 0;
        } else if (mainPlayer.row > 135) {
            mainPlayer.row = 135;
        }



        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons) != 0) {
          state = START;
          vBlankCounter = 0;
        } else
         if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons) != 0){
          state = TITLE;
          
          vBlankCounter = 0;


          drawFullScreenImageDMA(messi_title_image);
          drawString(20, 50, "Welcome to FIFA 2110", WHITE);
          drawString(45, 55, "Click Enter to play", WHITE);

        }

        break;
      case WIN:
        drawString(20, 10, "Congrats! Press Enter", WHITE);
        drawString(30, 10, "to play again", WHITE);
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons) != 0) {
          state = START;
          vBlankCounter = 0;

          //reset scores
          oppScore = 0;
          redCardCounter = 0;
          userScore = 0;

        } else if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons) != 0){
          state = TITLE;
          
          vBlankCounter = 0;


          drawFullScreenImageDMA(messi_title_image);
          drawString(20, 50, "Welcome to FIFA 2110", WHITE);
          drawString(45, 55, "Click Enter to play", WHITE);

        }


        break;
      case LOSE:
        drawString(20, 10, "You Lost!", WHITE);
        drawString(30, 10, "Press Enter", WHITE);
        drawString(40, 10, "to play again", WHITE);

        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons) != 0) {
          state = START;
          vBlankCounter = 0;

          //reset scores
          oppScore = 0;
          redCardCounter = 0;
          userScore = 0;
        } else if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons) != 0){
          state = TITLE;
          
          vBlankCounter = 0;


          drawFullScreenImageDMA(messi_title_image);
          drawString(20, 50, "Welcome to FIFA 2110", WHITE);
          drawString(45, 55, "Click Enter to play", WHITE);

        }


        break;
      
      case REF:
        drawString(20, 10, "You got 5 red cards! Chill Out!", WHITE);
        drawString(30, 10, "Press Enter", WHITE);
        drawString(40, 10, "to play again", WHITE);

        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons) != 0) {
          state = START;
          vBlankCounter = 0;
          
          //reset scores
          oppScore = 0;
          redCardCounter = 0;
          userScore = 0;
        } else if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons) != 0){
          state = TITLE;
          
          vBlankCounter = 0;


          drawFullScreenImageDMA(messi_title_image);
          drawString(20, 50, "Welcome to FIFA 2110", WHITE);
          drawString(45, 55, "Click Enter to play", WHITE);

        }


        break;

    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
